classDiagram
  %% User classes

  class User {
    +ObjectID _id
    +String username
    -String password
    +Array~Vote~ votes
  }

  User --> Vote

  class Vote {
    +Boolean like
    +Media media
  }

  Vote --> Media

  %% Group classes

  class Group {
    +ObjectID _id
    +String name
    +User owner
    +Array~User~ members

    +matches() Array~Match~
  }

  Group --> Match
  Group --> User

  class Match {
    +Int count
    +Media media
  }

  Match --> Media

  %% Media classes

  class Media {
    <<interface>>
    +Int id
    +MediaType media_type
    +String backdrop_path
    +Array~Int~ genre_ids
    +String original_language
    +String overview
    +Float popularity
    +String poster_path
    +Float vote_average
    +Int vote_count
  }

  class TMDbMovie {
    <<extends Media>>
    +Boolean adult
    +String original_title
    +String release_date
    +String title
    +Boolean video
  }

  class TMDbTv {    
    <<extends Media>>
    +String first_air_date
    +String name
    +String origin_country
    +String original_name
  }

  TMDbMovie ..|> Media
  TMDbTv ..|> Media
  Media --> MediaType

  class MediaType {
    <<enumeration>>
    movie
    tv
  }